### PR TITLE
Add Picture-in-picture support

### PR DESCRIPTION
**Pull request by suhan-paradkar**
This also adds support to multi-display, freeform windows and also for
secondary displays ... hopefully..

### CODE REVIEW

**Comment by suhan-paradkar** [comment]
Closes #8

@RalfWerner can you perform some tests for this artifact on secondary displays??

**Comment by RalfWerner** [comment]
> @RalfWerner can you perform some tests for this artifact on secondary displays??

This I've done [here](https://github.com/RalfWerner/integrated-process/issues/2#issuecomment-733700709)! In opposite to other XServers T:X11 has _no problems with **PiP!**_ Do you've a device with _**this**_ feature?
I'm just back from my holyday jurney and have not finished the [Question](https://github.com/suhan-paradkar/termux-wayland/issues/8#issue-940543643) description - please wait until I've finished.

**Comment by suhan-paradkar** [comment]
> This I've done [here](https://github.com/RalfWerner/integrated-process/issues/2#issuecomment-733700709)! In opposite to other XServers T:X11 has _no problems with **PiP!**_ Do you've a device with _**this**_ feature?

Okay..  I will check that out....
I have a device having PIP feature(Android 9).. but I wanted you to checkout if it works in android's partially implemented desktop mode...

> I'm just back from my holyday jurney and have not finished the [Question](https://github.com/suhan-paradkar/termux-wayland/issues/8#issue-940543643) description - please wait until I've finished.

Okay.. thats fine...

**Comment by RalfWerner** [comment]
> but I wanted you to checkout if it works in android's partially implemented desktop mode...

I read that PiP on all devices from Android 11 _should_ be possible, but it is _not._ Nice that you can do it and possibly repeat my check video? I've used there Touchscreen input modes: Direct and Emulated mouse but what do you mean by _"desktop mode"?_

**Comment by suhan-paradkar** [comment]
@RalfWerner To your clarification.. I mean android's desktop mode.. just like Samsung Dex... Not the input modes of the app...

**Comment by RalfWerner** [comment]
> To your clarification.. I mean android's desktop mode.. just like Samsung Dex.

Thanks for clarification! I've never used _"Samsung Dex"_ in the past, but have a SM-P610 (video) with comparable density to my PC monitor, using `scrcpy` to reflect and [BT-KB](https://github.com/termux/termux-app/issues/1995#issuecomment-843276188) and a BT-mouse.
Another possibility is the direct use of PC-XServer direct from termux XClients by `DISPLAY=...`.

**Comment by suhan-paradkar** [comment]
Closing in favour of #4

**Comment by suhan-paradkar** [comment]
Same as in #5

**Comment by RalfWerner** [comment]
I've checked **PiP-R** (Reseed screen) - it is available on AVD and also on my real Android 8-11 devices but _not_ with [PiP](https://github.com/suhan-paradkar/termux-wayland/discussions/19#discussion-3476183) on my Samsung comparable. [There](https://github.com/suhan-paradkar/termux-wayland/issues/8#issue-940543643) is PiP (Pop View) an app-independent extension of the Android _split_ function with free-scale/move, manage icons and transparency. This can also be used almost for all apps (not VNC) also Termux. Like _split_, the app can be fully used here inside the Picture limits. However, this is no longer possible with the activation of your PIP-R.

As far as I understood **PIP-R** and checked, the administration of two Picture sizes is possible, which can be moved grid-restricted. An interaction _in Picture_ is _**not**_ possible. This limits the possibility very one (Cofigure events only) and has none of the functions described above. So only the frequent swap in the fullscreen mode needed or _**did I miss something?**_

**Pull request merged**
